[package]
name = "dragula"
version = "0.1.0"
authors = ["Xavientois <joshua.rampersad@hotmail.com>"]
edition = "2018"
description = "Rust WASM wrapper for Dragula"
license = "MIT"
keywords = ["yew", "dragula", "frontend", "web"]
categories = ["gui", "wasm", "web-programming"]

[features]
default = []
yew-types = ["yew"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"

serde-wasm-bindgen = "0.1.2"

[dependencies.yew]
version = "0.17"
optional = true
